steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/frontend:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/frontend:$REVISION_ID"]
- name: 'busybox'
  args:
  - 'bash'
  - '-c'
  - |
    gsutil cp gs://container-kubernetes-key/node-example-gke-b8b874291782.json .
    gcloud auth activate-service-account --key-file=node-example-gke-b8b874291782.json
    gcloud container clusters get-credentials node-example-cluster --zone us-east1-b --project $PROJECT_ID
    kubectl set image deployment/frontend frontend=gcr.io/$PROJECT_ID/frontend:$REVISION_ID
